app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), index = True)
    email = db.Column(db.String(255),unique = True, index = True)
    bio = db.Column(db.String(1000))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    profile_pic_path = db.Column(db.String)
    password_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog',backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment',backref = 'user', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.password_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_secure,password)

    def __repr__(self):
        return f'User{self.username},{self.email}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'


class Blog(db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    description = db.Column(db.String(), index=True, nullable=False)    
    date_posted = db.Column(db.String)
    owner_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref =  'comment',lazy = "dynamic")


    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls,id):
        blogs = Blog.query.filter_by(blog_id=id).desc().all()
        return blogs

    @classmethod
    def get_blog(cls,id):
        blog = Blog.query.filter_by(id = id).first()

        return blog

    def __repr__(self):
        return f'Blog {self.description}'


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    description = db.Column(db.String(1000))
    name = db.Column(db.String)
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,blog_id):
        comments = Comment.query.filter_by(blog_id = blog_id).all()
        return comments

    @classmethod
    def delete_comment(cls,id):
        comment = Comment.query.filter_by(id=id).first()
        db.session.delete(comment)
        db.session.commit()

    def __repr__(self):
        return f'Comment{self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import *
from wtforms.validators import *
from ..models import User

class AddAuthor(FlaskForm):
	author = StringField('author name',validators=[Required()])

class BlogForm(FlaskForm):
    title = StringField('Title', validators = [Required()])
    description = TextAreaField('description',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    name = StringField('Name',validators=[Required()])
    description = TextAreaField('Add comment',validators=[Required()])
    submit = SubmitField()

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager



bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
 
    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, forms

app/main/views.py
from flask import render_template,redirect,url_for,abort, request
from . import main
from ..models import User,Blog, Comment
from .forms import BlogForm,AddAuthor, CommentForm
from .. import db
from flask.views import View, MethodView
from flask_login import login_required, current_user
import requests
import json


@main.route('/')
def index():
    
    blog = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()
    return render_template('index.html', blog = blog )

@main.route('/blog/new/', methods=['GET', 'POST'])
@login_required
def new_blog():
    '''
    Function that creates new bloges
    '''
    form = BlogForm()

    if form.validate_on_submit():
        title = form.title.data
        owner_id=current_user
        description = form.description.data
        
        
        new_blog = Blog(owner_id=current_user._get_current_object().id, title=title, description=description)

        new_blog.save_blog()
        return redirect(url_for('main.blog'))

    return render_template('new_blog.html', new_blog_form=form)

@main.route('/blog')
def blog():
    blogs = Blog.query.order_by(Blog.date_posted.desc())
    random = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()

    return render_template('blogs.html', blogs=blogs, random=random)


@main.route('/blogs/<int:blog_id>',methods = ["GET","POST"])
def view_blog(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first()
    random = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()
    form = CommentForm()
    if form.validate_on_submit():
        name = form.name.data
        description = form.description.data
        new_comment = Comment(name=name, description=description,blog_id=blog_id)
        new_comment.save_comment()
        return redirect(url_for('main.view_blog', blog_id=blog_id))
    comments = Comment.query.filter_by(blog_id=blog_id)
    
    return render_template("blog.html", blog_form=form, blog=blog, random = random, comments=comments)

@main.route("/delete/<blog_id>",methods = ['GET','POST'])
def delete(blog_id):
    blog = Blog.query.filter_by(id=blog_id).first()
    db.session.delete(blog)
    db.session.commit()

    return redirect(url_for('main.blog'))

@main.route('/<int:blog_id>/delete comments')
@login_required
def delete_comment(blog_id):
    comment = Comment.query.filter_by(blog_id=blog_id).first()
    blog_id = comment.blog_id

    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('main.view_blog', blog_id=blog_id))



    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block styles%}
    {{super()}}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


{% block content%}
<div class="container">
	
	<div class="row">
		
		<div class ="col-md-4"></div>
		<div class ="col-md-4">
			<div class="row">
				<h5 class="text-center" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">Published By: {{blog.user.username}}</h5>

			</div>
			<div class="row">
				<h1 class="text-center" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">{{blog.title}}</h1>

			</div>

			<div class="row">
				<p>{{blog.description}}</p>


			</div>

			
			<div class="row">
				<p>{{random.quote}}</p>

			</div>

			<div class="row">
				<h4 class="text-center" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">Comment: </h4>
				{{wtf.quick_form(blog_form)}}

			</div>
			<div class="row">
				<h3 class="text-center" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">Comments</h3>
			{% if comments %}
			{% for comment in comments%}
			<p>{{comment.description}} by {{comment.name}} </p>
			
				{% if current_user.is_authenticated%}
				<a href="{{url_for('main.delete_comment',blog_id = blog.id)}}">Delete</a>
				{% endif %}
			{% endfor%}
			{% else %}
			<p>There are no comments</p>
			{% endif %}
		
		</div>

		<div class="col-md-4"></div>
	</div>
</div>

{% endblock%}

app/templates/blogs.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}

{% block styles%}
{{super()}}

{% endblock %}


{% block content%}

<div class="container">
	<div align="center" class="row">
		<div class="row">
			<p class="text-center" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">{{random.quote}}</p>
			<p class="text-center" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">{{random.author}}</p>

		</div>

	</div>
	<div class="row">
		{% for blog in blogs %}
		
		<div align="center" class="col col-md-12">
			<div class="row">
				<div class="row">
					<h1>{{blog.title}}</h1>

				</div>

				<div class="row">
					<p>{{blog.description | truncate(40)}}

							<footer> Posted by {{blog.user.username}}</footer>
						
					</p>


				</div>
				<div class="row">
					<a href="{{url_for('main.view_blog',blog_id = blog.id)}}" class="btn btn-info" style="border-bottom: 2px solid #fca3b7; color: #000; padding-bottom: 10px;">Read More</a>


				</div>

			</div>

		</div>
		{% endfor%}


	</div>

</div>

{% endblock%}

app/templates/index.html
{% extends 'base.html'%}

<!-- Styles block -->

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
<link href="https://fonts.googleapis.com/css?family=Boogaloo" rel="stylesheet">
{% endblock %}

{% block content%}
<div class="container">
    <div class='jumbotron'>
        <div class="row" style="margin-top: 50px;">
          <div class="col-md-3"> </div>
          <div class="col-md-6" style="border: 1px solid #fca3b7; padding: 30px 10px; border-radius: 5px; font-size: 16px;">
    
        <h1 align='center'>READPRESS</h1>
        <hr>
        
{% endblock %}

app/templates/macros.html
{% macro displayPost(blog_list) %}
<div class="row">
	{% if blog_list %}
		{% for blog in blog_list %}
		<div class="col-md-6">
            <div class="panel panel-default">
      <div class="panel-heading">{{blog.title}}</div>
      <div class="panel-body">{{blog.description}}
      	<blockquote class="blockquote mb-0">
					<h2></h2>
					<footer class="blockquote-footer"> Posted by {{blog.user.username}}</footer>
				</blockquote></div>
                <div class="panel-footer"><a href="{{url_for('main.new_comment',blog_id = category.id)}}"> Add a comment</a>

</div>
    </div>

		</div>
		{% endfor %}
	{% else %}
	{% endif %}
</div>
{% endmacro %}



{% macro displayFullPost(blog_list) %}
<div class="row">
	{% if blog_list %}
		{% for blog in blog_list %}
		<div class="col-md-6">
            <div class="panel panel-danger">
      <div class="panel-heading">{{blog.title}}</div>
      <div class="panel-body">{{blog.description}}
      	<blockquote class="blockquote mb-0">
					<h2></h2>
					<footer class="blockquote-footer"> Posted by {{blog.user.username}}</footer>
				</blockquote></div>
                <div class="panel-footer"><a href="{{url_for('main.new_comment',blog_id = category.id)}}"> Add a comment</a>

</div>
    </div>

		</div>
		{% endfor %}
	{% else %}
	{% endif %}
</div>
{% endmacro %}


{% macro displayComment(comments) %}
<ul>

			{% if comments %}
			{% for comment in comments %}
				<div class="row text-center">
						<a><p style="color: brown">{{ comment.description }}</p></a>
						<small> posted by {{comment.user.username}}</small>
				</div>
			{% endfor %}
			{% else %}

			<h3>No comments</h3>
			{%endif%}

	</ul>


{% endmacro %}

app/templates/navbar.html
<div style="background-color: #fff; color: #fca3b7;" class="navbar" role="navigation" style="margin-bottom:0; border-bottom: 1px solid">
    <div class="container-fluid">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar" style="background-color: #fca3b7;"></span>
            <span class="icon-bar" style="background-color: #fca3b7;"></span>
            <span class="icon-bar" style="background-color: #fca3b7;"></span>
        </button>
        <a href="/" class="navbar-brand" style="color: #fca3b7;" onmouseover="this.style.color='#000'" onmouseout="this.style.color='#fca3b7'">ReadPress</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{url_for('main.blog')}}" style="color: #372e5f;" onmouseover="this.style.borderBottom='thick solid #372e5f'" onmouseout="this.style.borderBottom='none'">View Blogs</a></li>

                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.new_blog')}}" style="color: #372e5f;" onmouseover="this.style.borderBottom='thick solid #372e5f'" onmouseout="this.style.borderBottom='none'">New Blog</a></li>
                <li class="dropdown"><a style="color: #372e5f;" onmouseover="this.style.borderBottom='thick solid #372e5f'" onmouseout="this.style.borderBottom='none'" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                    aria-expanded="false">{{current_user.username| capitalize}} <span class="caret"></span></a>
                    
                </li>
                <li><a style="color: #372e5f;" onmouseover="this.style.borderBottom='thick solid #372e5f'" onmouseout="this.style.borderBottom='none'" href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a style="color: #372e5f;" onmouseover="this.style.borderBottom='thick solid #372e5f'" onmouseout="this.style.borderBottom='none'" href="{{url_for('auth.login')}}">Login</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</div>
        
    

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="row" style="margin-top: 50px">
  <div class="col-md-3"> </div>
  <div class="col-md-6" style="border: 1px solid #fca3b7; padding: 30px 10px; border-radius: 5px; font-size: 16px;">
    <h2 class="text-center" style="border-bottom: 2px solid #fca3b7; color: #fca3b7; padding-bottom: 10px;">{{legend}}</h2>
    {{ wtf.quick_form(new_blog_form) }}
  </div>
  <div clas="col-md-3"> </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <h2 class="text-center" style="color: #372e5f; border-bottom: 2px solid #372e5f; padding-bottom: 10px;"> {{user.username| capitalize}} </h2>
    <!--Display profile photo-->
    <div class="col-md-4">
      {% if user.profile_pic_path %}
      <img class="img-responsive img-circle" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}

      {% if user == current_user %}
      <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
        <input type="file" name="photo" class="form-control" required>
        <button class="btn" type="submit" style="margin-top: 10px; background-color: #372e5f; color: #fff;">Update Profile Picture</button>
      </form>
      {% endif %}
    </div>
    <div class="col-md-8">
        <h3 style="border-bottom: 1px solid #372e5f; padding-bottom: 10px; color: #372e5f;"> Bio </h3>
      <!--Displaying user bio-->
      {% if user.bio %}
      <p> {{user.bio}}</p>
      {%else%}
      <p> {{user.username}} has no bio </p>
      {% endif %}

      {% if user == current_user %}
      <a class="btn" style="background-color: #372e5f; color: #fff;" href="{{url_for('main.update_profile',uname=user.username)}}">Edit Bio</a>
      {% endif %}
    </div>
  </div>
  {% endblock %}
</div>

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}